services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./hello_world.py"
    depends_on:
      - mysql
    restart: always
    stdin_open: true
    tty: true

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
