version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_blibli
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
